In [ ]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
# Sentences
sent = ['the glass of milk',
        'the glass of juice',
        'the cup of tea',
        'I am a good boy',
        'I am a good developer',
        'understand the meaning of words',
        'your videos are good']

In [3]:
## Define the vocabulary size
voc_size = 10000

In [4]:
one_hot_repr = [one_hot(words, voc_size) for words in sent]
one_hot_repr

[[7243, 8677, 4599, 8079],
 [7243, 8677, 4599, 7386],
 [7243, 6253, 4599, 2183],
 [5866, 4894, 2957, 3057, 3901],
 [5866, 4894, 2957, 3057, 2074],
 [9649, 7243, 152, 4599, 798],
 [437, 5775, 9446, 3057]]

In [6]:
## Word Embedding Representation

from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

import numpy as np


In [8]:
# padding pre colocam zeros antes, padding post colocam zeros após os números gerados pelo oneHot
sent_length = 8
embedded_docs = pad_sequences(one_hot_repr, padding = 'pre', maxlen = sent_length)
print(embedded_docs)

[[   0    0    0    0 7243 8677 4599 8079]
 [   0    0    0    0 7243 8677 4599 7386]
 [   0    0    0    0 7243 6253 4599 2183]
 [   0    0    0 5866 4894 2957 3057 3901]
 [   0    0    0 5866 4894 2957 3057 2074]
 [   0    0    0 9649 7243  152 4599  798]
 [   0    0    0    0  437 5775 9446 3057]]


In [9]:
## Feature representation
dim = 10

In [10]:
model = Sequential()
model.add(Embedding(voc_size, dim, input_length = sent_length))
model.compile('adam', 'mse')

2025-05-02 16:38:38.051133: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:901] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2025-05-02 16:38:38.051404: W tensorflow/core/common_runtime/gpu/gpu_device.cc:2256] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...


In [11]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [12]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 32ms/step


array([[[-0.00801706,  0.02211226,  0.042338  , -0.03131732,
         -0.04155463, -0.01454792,  0.01867676,  0.0497619 ,
          0.04315354,  0.02799717],
        [-0.00801706,  0.02211226,  0.042338  , -0.03131732,
         -0.04155463, -0.01454792,  0.01867676,  0.0497619 ,
          0.04315354,  0.02799717],
        [-0.00801706,  0.02211226,  0.042338  , -0.03131732,
         -0.04155463, -0.01454792,  0.01867676,  0.0497619 ,
          0.04315354,  0.02799717],
        [-0.00801706,  0.02211226,  0.042338  , -0.03131732,
         -0.04155463, -0.01454792,  0.01867676,  0.0497619 ,
          0.04315354,  0.02799717],
        [ 0.00298997, -0.02343122,  0.00878202, -0.02971151,
          0.01189561,  0.00717815,  0.04574868,  0.00521431,
         -0.00486858, -0.00112215],
        [-0.03585766, -0.01007263,  0.03080907,  0.0274763 ,
         -0.04974842, -0.00742758,  0.04550037, -0.02306095,
          0.0044576 , -0.03150802],
        [ 0.01355555,  0.03054396,  0.0110653 , -0.0

In [13]:
embedded_docs[0]

array([   0,    0,    0,    0, 7243, 8677, 4599, 8079], dtype=int32)

In [14]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 10ms/step


array([[[-0.00801706,  0.02211226,  0.042338  , -0.03131732,
         -0.04155463, -0.01454792,  0.01867676,  0.0497619 ,
          0.04315354,  0.02799717],
        [-0.00801706,  0.02211226,  0.042338  , -0.03131732,
         -0.04155463, -0.01454792,  0.01867676,  0.0497619 ,
          0.04315354,  0.02799717],
        [-0.00801706,  0.02211226,  0.042338  , -0.03131732,
         -0.04155463, -0.01454792,  0.01867676,  0.0497619 ,
          0.04315354,  0.02799717],
        [-0.00801706,  0.02211226,  0.042338  , -0.03131732,
         -0.04155463, -0.01454792,  0.01867676,  0.0497619 ,
          0.04315354,  0.02799717],
        [ 0.00298997, -0.02343122,  0.00878202, -0.02971151,
          0.01189561,  0.00717815,  0.04574868,  0.00521431,
         -0.00486858, -0.00112215],
        [-0.03585766, -0.01007263,  0.03080907,  0.0274763 ,
         -0.04974842, -0.00742758,  0.04550037, -0.02306095,
          0.0044576 , -0.03150802],
        [ 0.01355555,  0.03054396,  0.0110653 , -0.0